# Generated by Django 3.1.11 on 2021-05-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('staff', models.CharField(max_length=5)),
                ('prompt_service', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=5)),
                ('recommend', models.CharField(max_length=5)),
                ('text_review', models.TextField()),
            ],
        ),
    ]
